// react/Components/List.tsx
import { Person } from "../Model/Person";

type Props = {
	persons: Person[];
	handleDetails: (id: number) => void;
};
export const List = ({ persons, handleDetails }: Props) => {
	return (
		<>
			<table>
				<thead>
					<th>id</th>
					<th>name</th>
					<th>age</th>
					<th>normal</th>
					<th>actions</th>
				</thead>
				<tbody>
					{persons.map((person) => (
						<tr>
							<td>{person.id}</td>
							<td>{person.name}</td>
							<td>{person.age}</td>
							<td>{person.normal ? "Yes" : "No"}</td>
							<td>
								<button onClick={() => handleDetails(person.id)}>
									Details
								</button>
							</td>
						</tr>
					))}
				</tbody>
			</table>
		</>
	);
};

// angular/app/list/list.component.ts
import { Component, EventEmitter, OnInit, Output, output } from "@angular/core";
import { Observable } from "rxjs";
import { Person } from "../../Model/Person";
import { PersonService } from "../Services/person.service";

@Component({
	selector: "app-list",
	standalone: false,

	templateUrl: "./list.component.html",
	styleUrl: "./list.component.css",
})
export class ListComponent implements OnInit {
	persons: Observable<Person[]>;
	@Output() details: EventEmitter<number | undefined>;
	constructor(private personService: PersonService) {
		this.persons = personService.persons;
		this.details = new EventEmitter<number | undefined>();
	}
	ngOnInit(): void {
		this.personService.load();
	}
	handleDetails(id: number) {
		this.details.emit(id);
	}
}

<table>
    <thead>
        <th>id</th>
        <th>name</th>
        <th>age</th>
        <th>normal</th>
        <th>actions</th>
    </thead>
    <tbody>
        @for (person of (persons|async); track person) {
        <tr>
            <td>{{person.id}}</td>
            <td>{{person.name}}</td>
            <td>{{person.age}}</td>
            <td>{{person.normal ? "Yes" : "No"}}</td>
            <td>
                <button (click)="handleDetails(person.id)">Details</button>
            </td>
        </tr>
        }
    </tbody>
</table>
